### PR TITLE
Add “elixir” filetype support

### PR DESCRIPTION
**Pull request by remi**
I added the `elixir` filetype support and kept the alphabetical order of the list.

### CODE REVIEW

**Review by fvictorio — APPROVED** [review]

**Comment by fvictorio** [comment]
Cool, thanks!

**Comment by remi** [comment]
I forgot to add a line in the supported languages table in `README.md`.  Will do another PR! 😄

**Comment by remi** [comment]
Oh, you just did! Thank you!

**Comment by fvictorio** [comment]
I already did it, don't worry :smile:

**Pull request merged**
